default:
  image: docker.io/library/alpine:latest
  before_script:
    - apk add -U --no-cache hugo py3-docutils

test:  # builds and tests your site on merge requests / other branches
  script:
    - hugo
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH

pages:  # deploys the compiled site to GitLab Pages on the default branch
  script:
    - hugo
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  environment: production
